language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: 7

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install
